### ISSUE TITLE
Example code for Flutter implementation

### ISSUE THREAD

**Issue by daadu** [shamblett/mqtt_client#26] opened 2018-08-14 09:40 UTC
I was looking for Flutter example for this package, but couldn't find one.

I don't know if this repo supports Flutter or not. At pub.dartlang.org it used to show flutter support but now it is unrecognised.

**Comment by shamblett** [comment] 2018-08-14 09:52
Yep, I'm updating it to Dart2 at the mo, lets see what it says when this is done.

**Comment by daadu** [comment] 2018-08-14 10:04
please add the example for flutter as well. Once done with updating with dart2.
I'm in the middle of development waiting for it.

**Comment by shamblett** [comment] 2018-08-14 10:07
I don't use flutter so I can't really write an example for it, when ready the existing flutter devs who are alos waiting will need to do this for me, I'll ask them. Note the Dart2 work is being tracked under Issue 24

**Comment by henkep** [comment] 2018-08-22 20:57
Hi
I will second what daadu said, I am also waiting for a Flutter example that I can use with Dart 2.0. Eagerly awaiting to start developing with this. :-)

**Comment by vinicentus** [comment] 2018-08-23 05:09
I'd also love to see an example in the coming weeks! Currently developing an application that uses mqtt...

**Comment by benbehringer** [comment] 2018-08-23 15:33
Thanks for the update! Cloned the most recent version from upstream and tested it with Flutter 0.7.0 Subtypes don't match: 

`I/flutter ( 9489): EXAMPLE::Mosquitto client connecting....
I/flutter ( 9489): EXAMPLE::Mosquitto client connected
I/flutter ( 9489): EXAMPLE::Publishing our topic
I/flutter ( 9489): EXAMPLE::Sleeping....
E/flutter ( 9489): [ERROR:flutter/shell/common/shell.cc(181)] Dart Error: Unhandled exception:
E/flutter ( 9489): type 'List<ChangeRecord>' is not a subtype of type 'List<MqttReceivedMessage<dynamic>>'
E/flutter ( 9489): #0      ChangeNotifier.deliverChanges (package:observable/src/change_notifier.dart:63:20)
E/flutter ( 9489): #1      _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
E/flutter ( 9489): #2      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
I/flutter ( 9489): EXAMPLE::Unsubscribing
I/flutter ( 9489): EXAMPLE::Disconnecting`

Going to incorporate a workaround for flutter in my fork.

**Comment by josvos** [comment] 2018-08-27 12:34
Except for this problem @shamblett's code seem to be compatible with the current Flutter version (althought fact is that I can't get it working at all due to this).  What would your fork add to the upstream version?

**Comment by daadu** [comment] 2018-08-27 18:40
@benbehringer I depend on your clone for production version (not published yet). Please don't break!!

**Comment by henkep** [comment] 2018-08-27 18:55
Is anyone using this with TLS? I am trying to connect to my broker on a custom TLS port but it can´t connect.

**Comment by josvos** [comment] 2018-08-27 19:18
@daadu: note that @benbehringer's fork is not compatible with the latest Flutter due to dependency issues (SDK).

**Comment by shamblett** [comment] 2018-08-28 09:19
TLS does work, see the iot_core.dart example, if your port is non standard you will have to set it explicitly, 
and of course set secure.

// Set the port
  client.port = port;
  // Set secure
  client.secure = true;

**Comment by shamblett** [comment] 2018-08-28 10:25
OK, Dart 2.0 work now complete, please test the new 3.0.0 client, see issue 24 for more detail.

**Comment by henkep** [comment] 2018-08-28 13:16
Hi again
I started a new flutter project, ran flutter upgrade and then added mqtt_client: ^3.0.0 to my pubspec.yaml file. But the package get fails with this error regarding typed_data:

Because every version of flutter_test from sdk depends on typed_data 1.1.5 and mqtt_client >=3.0.0 depends on typed_data ^1.1.6, flutter_test from sdk is incompatible with mqtt_client >=3.0.0.
So, because new_mqtt depends on both mqtt_client ^3.0.0 and flutter_test any from sdk, version solving failed.

Any ideas?

**Comment by henkep** [comment] 2018-08-28 13:32
Sorry, my bad. I was on the beta channel of flutter and not the dev channel. Tried it now and it downloads the package just fine, now on to getting TLS to work. :-)

**Comment by daadu** [comment] 2018-09-02 00:58
I moved from:
```
mqtt_client:
    git:
      url: https://github.com/benbehringer/mqtt_client.git
```

to:
```
mqtt_client: ^3.0.0
```

It is working as expected. But I'm getting the following warning. 
```
file:///home/user/flutter/.pub-cache/hosted/pub.dartlang.org/mqtt_client-3.0.0/lib/src/connectionhandling/mqtt_client_mqtt_secure_connection.dart:68:26: Warning: Can't return a value from a void function.
return completer.complete();
```

is it something to worry about?

**Comment by shamblett** [comment] 2018-09-02 09:07
Shouldn't sop anything working, its already been spotted and being tracked under issue 27. I'll update the package when a fix has been confirmed by the flutter guys.

**Comment by josvos** [comment] 2018-09-02 11:28
Not solved yet (AFAICS), see my latest comment in issue #27.

**Comment by shamblett** [comment] 2018-10-06 13:29
Flutter example now added, package republished at 3.3.3

**Closed by shamblett** 2018-10-06 13:29 UTC
Labels: help wanted
